name: SEO Wizard
favicon: null
layout_spectrum: 0.051832337165251374
typography_spectrum: 0.43436631304211915
title: The SEO Wizard
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.46537069394253194
  lightness: 0.6062521680723876
  saturation: 0.7605118977371603
  rhythmicContrast: 0.9465647449251264
purpose: []
